<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="Dapper" Version="2.1.11" />-->
    <PackageReference Include="Dapper" Version="1.50.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <!-- System.Runtime.CompilerServices.Unsafe handled transitively from newer packages on nuget.org -->
  </ItemGroup>

</Project>
