<Project Sdk="Microsoft.NET.Sdk.Web">


  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <!-- System.Runtime.CompilerServices.Unsafe handled transitively from newer packages on nuget.org -->
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\JasonCarter.BudgetDashboard.Business\JasonCarter.BudgetDashboard.Business.csproj" />
    <ProjectReference Include="..\JasonCarter.BudgetDashboard.Common\JasonCarter.BudgetDashboard.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
